### ISSUE TITLE
crashed when I accessed the config

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Tre5et/ridehud#1]
https://mclo.gs/qRif4PM

**Comment by Aces-and-Jacks** [comment]
Was this closed because it's 4 months old or was it because it wasn't caused by this mod?

**Comment by Tre5et** [comment]
I closed this issue, because I kinda forgot it existed until just now (sorry) and the link to the logs doesn't work (anymore?). 
However, if you are still affected by this, and you can provide logs, I will try to take a look at it. 
No promises though, as I generally don't have the time to support older Minecraft (sub-)versions.

**Comment by Aces-and-Jacks** [comment]
Oh ok. Didn't notice that the log was no longer up. On a positive note I know after a certain amount of time that the log gets deleted if no one opens it

**Comment by Aces-and-Jacks** [comment]
Honestly I don't really play as much as I used to. The only thing Minecrafty I do that I just can't stop doing is browse modrinth for interesting client mods and add them to my personal modpack

**Comment by Aces-and-Jacks** [comment]
If your still willing to take a look at the log for anyone else on 1.19.2 https://mclo.gs/qoYJVNf

**Comment by Tre5et** [comment]
Alright, this is a known issue with VanillaConfig on 1.19.2. I didn't play Minecraft a lot during that version and just updated it, tested it once and assumed it was fine until someone reported this issues on one of my other mods months later.
Again, as I don't have time to support older subversions, there won't be a release that fixes this. If you are still interested in having this fixed, here is a version of VanillaConfig that works for 1.19.2. Keep in mind though that it is largely untested otherwise.
[vanillaconfig-1.2.2+1.19.x-crash-patch.zip](https://github.com/Tre5et/ridehud/files/11731807/vanillaconfig-1.2.2%2B1.19.x-crash-patch.zip)

**Comment by Aces-and-Jacks** [comment]
Ok. Thanks
