### ISSUE TITLE
Adding Russian localization

### ISSUE THREAD

**Issue by dimeetrue** [Tre5et/ridehud#5]
[ru_ru.json](https://github.com/user-attachments/files/17282541/ru_ru.json)

Hello. I would like to ask you to add a translation into Russian, if you don't mind. 
Also, during the translation in the "config.ridehud.display_text" tab: you can select On or Off, but there is no way to translate this in the config. It's not critical, but I wanted to talk about it. Thanks for the mod.

**Comment by Tre5et** [comment]
Hi, thanks for these translations, I will gladly add them to the project.
If you want to, you can [fork the project](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#forking-a-repository) and [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request) with the changes, then you'll be listed as a contributor ;).
Otherwise, just let me know and I'll put the translations in myself.

The `On` and `Off` text come from the config library [VanillaConfig](https://github.com/Tre5et/vanillaconfig), which I am also the developer of.
If you want to add them too, you can do exactly the same in that project (of course you don't need to translate the rest of the string from VanillaConfig if you don't want to), or just let me know.
